config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :comments
  end
  resources :schedules
  resources :events

  root 'events#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates_presence_of :event
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @new_comment = Comment.new
  end

  def show
    @comment = Comment.find_by(id: params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @comment }
    end
  end

  def create
    @user = User.find_by(id: params[:user_id])
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to request.referer, flash: {notice: 'Thanks for commenting.'}
    else
      redirect_to request.referer, flash: {alert: 'Could not post comment.'}
    end
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
    @user = @comment.user
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    authorize @comment
    @comment.update(comment_params)
    redirect_to request.referer, flash: {notice: 'Comment was updated.'}
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    authorize @comment
    @comment.delete
    redirect_to request.referer, flash: {notice: 'Comment was removed.'}
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id, :event_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div class="card card-event-relative">
  <%= render 'comments/new_comment' if @event %>
<h4>Comments:</h4>
<ul>
  <% if @comments.present? %>
    <% @comments.each do |comment| %>
      <% if comment.persisted? %>
        <li><%= comment.content %> : by <%= link_to comment.user.name, user_path(comment.user) %>
          <% if user_signed_in? %>
            <%= link_to 'Edit', edit_user_comment_path(comment.user, comment), class: 'button' if policy(comment).update? %>
            <%= button_to "X", [comment.user, comment], :method => :delete, class: 'button cancel' if policy(comment).update? %></li>
          <% end %>
      <% end %>
    <% end %>
  <% else %>
    <li>
      No comments yet!
    </li>
  <% end %>
</ul>

</div>

app/views/comments/_form.html.erb
<div class="info">
  <%= form_for [@comment.user, @comment] do |f| %>
    <%= f.text_area :content %>
    <%= f.submit 'Make this change', :class => 'button confirm' %>
    <% end %>
<%= button_to "X", [@comment.user, @comment], :method => :delete, class: 'button cancel' %></li>
</div>

app/views/comments/_new_comment.html.erb
<% if user_signed_in? %>
  <h4>Make a new comment:</h4>
  <%= form_for [current_user, @new_comment] do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <% if @event %>
      <%= f.hidden_field :event_id, :value => @event.id %>
    <% else %>
      <%= f.collection_select :event_id, Event.all, :id, :name %>
    <% end %>
    <%= f.submit "Comment!", class: 'button' %>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/comments/new.html.erb
<%= render 'new_comment' %>

app/views/comments/show.html.erb
<div class="card card-event">
  <h3><%= @comment.user.name %> said:</h3>
  <p>
    <%= @comment.content %>
  </p>
  <p>
    <%= link_to 'Edit', edit_user_comment_path(id: @comment.id, user_id: @comment.user.id), class: 'button' if policy(@comment).update? %>
    <%= button_to "X", [@comment.user, @comment], :method => :delete, class: 'button cancel' if policy(@comment).update? %>
  </p>
</div>