config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :comments
  end
  resources :schedules
  resources :events

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :organizer, :foreign_key => "user_id", :class_name => 'User'
  has_many :schedules
  has_many :users, through: :schedules#, source: :user
  has_many :comments
  has_many :event_tags
  has_many :tags, through: :event_tags
  accepts_nested_attributes_for :tags
  has_attached_file :cover_image, default_url: ':style/image-placeholder.jpg', styles: { thumb: "200x200>" }
  validates_attachment_content_type :cover_image, content_type: /\Aimage\/.*z/
  validates_attachment_file_name :cover_image, matches: [/png\z/, /jpe?g\z/ ]
  do_not_validate_attachment_file_type :cover_image
  validates_presence_of :description, :name, :location, :start_time, :end_time
  # validate :event_cannot_start_in_the_past, :event_cannot_end_before_start_time
  validate :has_valid_times

  def start_time
    super.in_time_zone(time_zone) if time_zone
  end

  def end_time
    super.in_time_zone(time_zone) if time_zone
  end

  def self.sorted_by_start_time
    self.all.order('start_time')
  end

  def readable_start_time
    self.start_time.strftime("%A, %d %b %Y %l:%M %p")
  end

  def readable_end_time
    self.end_time.strftime("%A, %d %b %Y %l:%M %p")
  end

  def tags_attributes=(tag_attributes)
    tag_attributes.values.each do |tag_attribute|
      tag = Tag.find_or_create_by(tag_attribute) if tag_attribute[:name].present?
      self.tags << tag if tag
    end
  end

  def has_valid_times
    event_cannot_start_in_the_past
    event_cannot_end_before_start_time
    event_has_duration
  end

  def event_has_duration
    errors.add(:end_time, "Event has to have a duration") if start_time == end_time
  end

  def event_cannot_start_in_the_past
    if self.start_time.present? && self.start_time < DateTime.now
      errors.add(:start_time, "Event cannot start in the past")
    end
  end

  def event_cannot_end_before_start_time
    if self.end_time.present? && self.start_time.present? && self.end_time < self.start_time
      errors.add(:start_time, "Event cannot end before it starts.")
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.sorted_by_start_time
    respond_to do |format|
      format.html
      format.json { render json: @events }
    end
  end

  def show
    @event = Event.find(params[:id])
    @users = @event.users
    @new_comment = current_user.comments.new if user_signed_in?
    @comments = @event.comments
    @tags = @event.tags
    @event_tags = @event.tags
    respond_to do |format|
      format.html
      format.json {render json: @event }
    end
  end

  def new
    @event = current_user.events.build
  end

  def create
    Time.zone = params[:event][:time_zone]
    @event = current_user.events.build(event_params)
    @event.organizer = current_user
    if authorize @event
      if @event.save
        render json: @event
      else
        render :new, flash: {error: 'Uh oh'}
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
    @users = @event.users
    @user = current_user
  end

  def update
    @event = Event.find(params[:id])
    Time.zone = @event.time_zone
    if authorize @event
      if @event.update(event_params)
        render json: @event
      else
        render :edit, flash: {error: 'Uh oh'}
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    authorize @event
    if @event.delete
      redirect_to events_path, flash: {message: 'Event was succussfelly removed.'}
    else
      render :show
    end
  end

  private
    def event_params
      params.require(:event).permit(:name, :description, :location, :start_time, :end_time, :time_zone, :cover_image, tag_ids: [], tags_attributes: [:name])
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="card panel-group <%= col %>" id="event-<%= event.id %>">
  <div class="pull-right">
    <!-- <button class="js-more button" data-id="<%= event.id %>">More Info</button> -->
    <%= link_to 'Edit', edit_event_path(event), class: 'button btn-overlay' if user_signed_in? && event.organizer == current_user %>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="card_photo">
        <a href="#">
          <!-- todo add event photo -->
          <div class="card_photo_image">
          </div>
        </a>
      </div>
    </div>
    <div class="panel-body">
      <h4>
        <strong><%= link_to event.name, event_path(event) %> by <%= link_to event.organizer.name, user_path(event.organizer) %></strong>
      </h4>

      <p>
        <strong>Location:</strong> <%= event.location %>
      </p>

      <div id="event-<%= event.id %>-detail">
        <p><%= event.readable_start_time %> to <%= event.readable_end_time %></p>
        <span><%= event.description %></span>
      </div>

    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event, :remote => true, :html => { :multipart => true }) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :location %><br>
  <%= f.text_field :location %><br>
  <%= f.label :start_time %><br>
  <%= f.time_zone_select('time_zone', ActiveSupport::TimeZone.us_zones, default: "Pacific Time (US & Canada)")  %><br>
  <%= f.datetime_select :start_time, :ampm => true, :min => DateTime.now, :default => DateTime.now.beginning_of_hour + 1.hour %><br>
  <%= f.label :end_time %><br>
  <%= f.datetime_select :end_time, :ampm => true, :min => DateTime.now, :default => DateTime.now.beginning_of_hour + 1.hour + 15.minutes %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :cover_image %>
  <%= f.file_field :cover_image %>

  <p>
  <h4>Tags:</h4>
  <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br>
  <%= f.label :tags, 'Make a new Tag' %>
  <%= f.fields_for :tags, @event.tags.build do |tag_fields| %>
    <%= tag_fields.text_field :name %>
  <% end %>
  </p>
  <%= f.submit 'Submit', :class => 'button confirm' %>
<% end %>
<p>
  <%= button_to "Cancel this Event", event_path(@event), :method => :delete, class: 'button cancel' if policy(@event).destroy? && @event.persisted? %></li>
</p>

app/views/events/_messages.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@event.errors.count, "error") %>
      prohibited this event from being saved:
    </h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render 'messages' %>

<div class="row">
  <div class="panel-group col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Edit this event</h3>
      </div>
      <div class="panel-body">
        <div class="card card-event form">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
<!-- <script id="event-template" type="text/x-handlebars-template">
  <h4>
    <strong><a href="/events/{{id}}">{{name}}</a> by <a href="/users/{{organizer.id}}">{{organizer.name}}</a></strong>
  </h4>
  <p><strong>Location:</strong> {{location}}</p>
  <p><strong>Begins:</strong> {{readable_start_time}}</p>
  <p><strong>Ends: </strong> {{readable_end_time}}</p>
  <p><strong>Description:</strong> {{description}}</p>
  <p><a class="button" href="/events/{{id}}/edit">Edit this event</a></p>
</script> -->

app/views/events/index.html.erb
<h4>Browse Events</h4>

  <div class="row">

    <div class="col-sm-9">
      <div class="row">
          <%= render @events, col: 'col-sm-6' %>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              Advertisements
            </div>
            <div class="panel-body">
              Space for Ads
            </div>
          </div>
        </div>
    </div>

  </div>

app/views/events/new.html.erb
<%= render 'messages' %>
<div class="row">
  <div class="panel-group col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Create a new event</h3>
      </div>
      <div class="panel-body">
        <div class="card card-event form">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- <script id="event-template" type="text/x-handlebars-template">
  <h4>
    <strong><a href="/events/{{id}}">{{name}}</a> by <a href="/users/{{organizer.id}}">{{organizer.name}}</a></strong>
  </h4>
  <p><strong>Location:</strong> {{location}}</p>
  <p><strong>Begins:</strong> {{readable_start_time}}</p>
  <p><strong>Ends: </strong> {{readable_end_time}}</p>
  <p><strong>Description:</strong> {{description}}</p>
  <p><a class="button" href="/events/{{id}}/edit">Edit this event</a></p>
</script> -->

app/views/events/show.html.erb
<div class="row">
    <%= render @event, col: 'col-sm-8' %>

  <div class="panel-group col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><%= 'Attender'.pluralize(@users.count) %> of this Event:</h4>
      </div>

      <div class="panel-body">
        <div class="card card-event">
          <div id="users">
            <button class="js-users button" data-id="<%= @event.id %>">Who's Going?</button>
          </div>

          <p>
            <% if user_signed_in? %>
              <%= form_tag schedules_path, method: 'POST' do %>
                <%= hidden_field_tag :user_id, current_user.id %>
                <%= hidden_field_tag :event_id, @event.id %>
                <%= submit_tag "Go to this event", class: 'button confirm' %>
              <% end %>
              <%=  button_to "Not going anymore", {:controller => :schedules, :action => 'destroy', :id => @event.id}, :method => :delete, class: 'button cancel' unless @users.nil? %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-group col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        Comments
      </div>
      <div class="panel-body">
        <%= render 'comments/comments' %>
        <%= render 'tags/tags' %>
      </div>
    </div>
  </div>
</div>