config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :comments
  end
  resources :schedules
  resources :events

  root 'events#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :event_tags
  has_many :events, through: :event_tags

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def index
      @tags = Tag.all
    end

    def show
      @tag = Tag.find_by(id: params[:id])
      @events = @tag.events
    end

    def create
      @event = Event.find_by(id: params[:tag][:event_id])
      @tag = Tag.find_or_create_by(name: tag_params[:name])
      @event.tags << @tag unless @event.tags.include?(@tag)
      if @tag.save
        redirect_to request.referer, flash: {notice: 'You have sucessfully tagged this event'}
      else
        redirect_to request.referer, flash: {error: 'Could not tag this event'}
      end
    end

    private
      def tag_params
        params.require(:tag).permit(:event_id, :name)
      end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_tags.html.erb
<div class="card card-event">
  <h4><%= 'Tag'.pluralize(@tags.count) %>:</h4>
  <p>
    <% @tags.map do |tag| %>
      <%= link_to tag.name, tag_path(tag), class: "button" %>
    <% end %>
  </p>
</div>

app/views/tags/index.html.erb
<ul>
  <% @tags.each do |tag| %>
    <li><%= link_to tag.name, tag_path(tag) %></li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h3>Events tagged with <strong>"<%= @tag.name %>"</strong></h3>

<%= render @events %>